/*function func() {
    console.log("Ran successfuly..");
}

try{
    func();
    funct2();
}catch(err) {
    console.log(err.name);
    console.log(err.message);
    console.log(err);
}*/
